services:
  web-app:
    build: 
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./config:/config
    environment:
      - DB_HOST=database
      - DB_NAME=test
      - DB_USER=uran
      - DB_PASS=1

    command: >
      sh -c "python3 manage.py runserver 0.0.0.0:8000"
    depends_on:
      - database
    links:
      - database:database

  database:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=uran
      - POSTGRES_PASSWORD=1