# Generated by Django 4.2.2 on 2023-06-28 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Ф.И.О')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Эл.почта')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('gender', models.CharField(max_length=10, verbose_name='Пол')),
                ('picture', models.ImageField(upload_to='student_images/')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='group.group', verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Ученик(ца)',
                'verbose_name_plural': 'Ученики(цы)',
            },
        ),
    ]
